<?xml version="1.0"?>
<robot name="robot_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ============================================ -->
  <!-- ARQUIVO PRINCIPAL                            -->
  <!-- Importa propriedades e macros, define o robô -->
  <!-- ============================================ -->

  <!-- ==================== -->
  <!-- IMPORTAÇÃO DE ARQUIVOS -->
  <!-- ==================== -->
  <!--
    xacro:include importa o conteúdo de outros arquivos .xacro
    $(find package_name) retorna o caminho do pacote ROS
  -->
  <xacro:include filename="$(find rm_description)/urdf/properties.xacro"/>
  <xacro:include filename="$(find rm_description)/urdf/macros.xacro"/>

  <!-- ==================== -->
  <!-- BASE FOOTPRINT       -->
  <!-- ==================== -->
  <link name="base_footprint"/>

  <!-- ==================== -->
  <!-- BASE LINK            -->
  <!-- ==================== -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia
        ixx="${(1/12) * base_mass * (3*base_radius*base_radius + base_height*base_height)}"
        ixy="0.0" ixz="0.0"
        iyy="${(1/12) * base_mass * (3*base_radius*base_radius + base_height*base_height)}"
        iyz="0.0"
        izz="${(1/2) * base_mass * base_radius * base_radius}"/>
    </inertial>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- ==================== -->
  <!-- LINK 1 (usando macro) -->
  <!-- ==================== -->
  <!-- TAREFA: Chame o macro cylinder_link para criar o link1 -->
  <!-- Parâmetros: name, length, radius, mass, material -->
  <xacro:cylinder_link
    name="link1"
    length="${link1_length}"
    radius="${link1_radius}"
    mass="${link1_mass}"
    material="blue"/>

  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi}" upper="${pi}" effort="10" velocity="1.0"/>
  </joint>

  <!-- ==================== -->
  <!-- LINK 2 (usando macro) -->
  <!-- ==================== -->
  <!-- TAREFA: Chame o macro cylinder_link para criar o link2 -->
  <xacro:cylinder_link
    name="link2"
    length="${link2_length}"
    radius="${link2_radius}"
    mass="${link2_mass}"
    material="green"/>

  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${link1_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi*0.75}" upper="${pi*0.75}" effort="10" velocity="1.0"/>
  </joint>

  <!-- ==================== -->
  <!-- END EFFECTOR         -->
  <!-- ==================== -->
  <!-- TAREFA: Use o macro sphere_link para criar o end_effector -->
  <xacro:sphere_link
    name="end_effector"
    radius="${ee_radius}"
    mass="${ee_mass}"
    material="red"/>

  <joint name="end_effector_joint" type="fixed">
    <parent link="link2"/>
    <child link="end_effector"/>
    <origin xyz="0 0 ${link2_length}" rpy="0 0 0"/>
  </joint>

</robot>